---
sidebar: sidebar 
permalink: ai-policy.html 
keywords: AI, artificial intelligence, generated content, NetApp, technical documentation 
summary: NetApp의 정책은 사람에 의해 검증되고 검증되지 않은 AI 생성 콘텐츠의 게시를 금지하는 것입니다. 
---
= NetApp 기술 문서에 AI 생성 콘텐츠가 사용되는 것을 금지하는 정책
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 고객을 위해 정확하고 연관성이 있으며 유용한 기술 문서를 작성, 게시, 유지 관리하는 데 있어 직원, 계약업체 및 파트너의 전문성을 매우 중요하게 생각합니다. NetApp은 AI에서 생성된 콘텐츠를 사용할 경우 이러한 가치가 훼손되고 문서의 무결성과 정확성이 떨어질 수 있다고 생각합니다. 따라서 NetApp의 정책은 사람이 확인 및 검증하지 않은 AI 생성 콘텐츠의 게시를 금지하는 것입니다. 이 내용은 docs.netapp.com 게시된 모든 기술 문서에 적용됩니다. 이 정책은 판매하는 제품에 대해 언어 모델을 사용하지 않는 것이 좋습니다.

모든 NetAppDocs 참가자는 다음 정책을 준수해야 합니다.

* AI에서 생성된 고객 대면 문서(NetApp 제품 사용 방법)를 인간의 검토 및 검증을 거치지 않고 출판할 수 없습니다. 여기에는 docs.netapp.com 게시된 서면 자료, 그래픽, 멀티미디어 또는 기타 자료가 포함됩니다. docs.netapp.com 에 게시된 모든 콘텐츠는 인간 콘텐츠 제작자의 확인 및 검증을 받아야 합니다.
* docs.netapp.com 콘텐츠 제작자의 역할은 스타일 및 기여자 가이드를 준수하는 것입니다. 여기에는 AI 생성 콘텐츠의 최신 개발과 NetApp 기술 문서에 대한 시사점에 대한 최신 정보가 포함되어 있습니다.
* 모든 직원, 계약업체 및 파트너는 이 정책을 준수해야 합니다. 반복적으로 위반하면 제작 권한이 일시 중단될 수 있습니다.


NetApp Docs 참가자는 다음을 염두에 두어야 합니다.

* Microsoft 365 공동 파일럿과 같은 소프트웨어를 포함하여 업무용 컴퓨터에 설치된 소프트웨어에 포함된 모든 AI 기반 콘텐츠 생성 기술은 보조 기술을 호스팅하는 회사에 데이터를 전송합니다. 공개되지 않은 제품 기능에 대한 사양을 포함하나 이에 국한되지 않는 회사 기밀 콘텐츠가 포함된 이러한 기술을 표시하지 마십시오.
* 공개 AI 기술을 사용하여 **이전 미출시** 제품, 제품 버전 또는 제품 내 기능에 대한 기술 문서를 생성하거나 편집하지 마십시오.
* 새로운 기술 문서에 대한 저작권은 NetApp에 있으며 공식 제품 릴리즈 날짜 이전에 NetApp 외부의 AIS와 관련 기술 문서의 발행에 포함되지 않습니다.
* 기밀 문서 또는 새로 작성된 콘텐츠를 AI(ChatGPT 또는 기타 도구)로 보내지 마십시오. ChatGPT에 공급되는 모든 정보는 교육 데이터 세트의 일부가 되며, 이 데이터 세트는 OpenAI의 자산이 되고 이를 통해 사용자와 해당 사용자가 사용할 수 있습니다. 이러한 데이터의 대부분은 공개적으로 액세스할 수 있지만, 우리는 자사 IP를 통해 모델을 교육하고 싶지 않습니다.

