---
sidebar: sidebar 
permalink: ai-policy.html 
---
= NetApp 기술 문서에 AI 생성 콘텐츠가 사용되는 것을 금지하는 정책
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp은 직원, 계약자 및 파트너의 창의성과 전문성을 활용하여 고객을 위한 정확하고 연관성이 높은 유용한 기술 문서를 작성, 게시 및 유지 관리합니다. NetApp은 AI에서 생성된 콘텐츠를 사용할 경우 이러한 가치가 훼손되고 문서의 무결성과 정확성이 떨어질 수 있다고 생각합니다. 따라서 NetApp의 정책은 docs.netapp.com 에 게시된 모든 기술 문서에서 AI 기반 콘텐츠를 사용하는 것을 금지하는 것입니다. 이 정책은 판매하는 제품에 대해 언어 모델을 사용하지 않는 것이 좋습니다.

모든 NetAppDocs 참가자는 다음 정책을 준수해야 합니다.

. * AI 생성 콘텐츠 사용에 대한 금지: * 고객을 위해 생성되는 기술 문서에 AI 생성 콘텐츠를 사용하는 것은 허용되지 않습니다. 여기에는 netapp.com 게시된 서면 자료, 그래픽, 멀티미디어 또는 기타 자료가 포함됩니다. docs.netapp.com 에 게시된 모든 콘텐츠는 NetApp의 직원, 계약자 또는 파트너가 자체 창의성, 전문성 및 경험을 사용하여 만들어야 합니다.
. * 교육 및 훈련: * 당사는 직원, 계약업체 및 파트너에게 AI 생성 콘텐츠의 사용과 관련하여 정기적으로 교육과 교육을 제공하며, 기술 문서에 이를 허용하지 않는 이유를 제공합니다. NetApp은 귀사와 관련된 모든 개인에게 AI 생성 콘텐츠의 최신 개발과 NetApp 기술 문서에 대한 시사점에 대한 최신 정보를 제공할 것을 권장합니다.
. * 규정 준수 및 보고: * 모든 직원, 계약업체 및 파트너는 이 정책을 준수할 책임이 있습니다. 본 정책의 위반 또는 위반이 의심되는 경우 즉시 NetApp 법무 부서에 조사를 의뢰해야 합니다.


NetApp Docs 참가자는 다음을 염두에 두어야 합니다.

* AI를 사용하여 이전에 릴리즈되지 않은 제품, 제품 버전 또는 제품 내 기능에 대한 기술 문서를 생성하거나 편집하지 마십시오.
* 새로운 기술 문서에 대한 저작권은 NetApp에 있으며 공식 제품 릴리즈 날짜 이전에 NetApp 외부의 AIS와 관련 기술 문서의 발행에 포함되지 않습니다.
* URL을 포함하여 2021년 이후에 작성된 기밀 문서, 새 콘텐츠 또는 콘텐츠를 AI(ChatGPT 또는 기타 툴)로 보내지 마십시오. ChatGPT에 공급되는 모든 정보는 교육 데이터 세트의 일부가 되며, 이 데이터 세트는 OpenAI의 자산이 되고 이를 통해 사용자와 해당 사용자가 사용할 수 있습니다. 이러한 데이터의 대부분은 공개적으로 액세스할 수 있지만, 우리는 자사 IP를 통해 모델을 교육하고 싶지 않습니다.

