---
sidebar: sidebar 
permalink: style.html 
---
= NetApp 문서의 스타일 가이드
:toc: macro
:hardbreaks:
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
우리의 스타일은 대화적이고 공감적이지만, 우리는 전문가답게 대화를 나누며 요점을 얻습니다. NetApp 문서의 콘텐츠를 작성할 때 다음 지침을 따르십시오.



== 대화식으로 쓰기

전문 동료에게 무언가를 설명할 때 말하는 것처럼 쓰십시오. 대화 어조로 글을 작성하면 청중과 소통할 수 있습니다.


TIP: 글을 크게 읽습니다. 미국의 소설가이자 영화작가인 엘More 레오나드는 “글씨를 쓰는 것 같다면 다시 쓰겠습니다.”라고 말했습니다.

|===
| 너무 격식적인 | 너무 캐주얼합니다 | 우리의 스타일 


| Cloud Tiering에 문제가 발생한 경우 클러스터 대시보드에서 상태 를 확인하여 오류가 발생한 원인을 파악할 수 있습니다. 상태는 ONTAP 시스템 및 서비스 커넥터 상태를 반영합니다. | 오류가 발생할 때 재미가 없습니다. 하지만 걱정하지 마십시오. 클러스터 대시보드를 확인하여 어떤 일이 발생했는지, 어떤 영향이 있는지 확인하십시오. | 오류가 발생하면 Cloud Tiering은 클러스터 대시보드에 "Failed" 상태를 표시합니다. 상태를 보고 실패에 대한 정보를 봅니다. 


| 클라우드 계층화에 대한 비용을 여러 방법으로 지불할 수 있습니다. 사용한 만큼만 지불하는 구독을 통해 클라우드 계층화에 대한 비용을 지불하거나, ONTAP 계층화 라이센스를 통해 비용을 지불하거나, 두 가지를 결합하여 비용을 지불할 수 있습니다. Cloud Manager 내에서 라이센스를 받을 수 없으며 Cloud Tiering 서비스로 직접 이동하여 설정해야 합니다. | 클라우드 계층화에 대한 비용을 지불할 수 있는 세 가지 방법을 원합니다. 용량제 구독, ONTAP 계층화 라이센스 또는 두 가지를 결합하는 것도 가능합니다. Cloud Manager에서는 라이센스를 얻을 수 없으므로 Cloud Tiering 서비스로 이동하여 설정하기만 하면 됩니다. | 사용한 만큼만 지불하는 가입형, ONTAP 계층화 라이센스 또는 둘 모두를 결합하여 Cloud Tiering에 대한 비용을 지불하십시오. Cloud Manager 내에서는 라이센스를 사용할 수 없지만 Cloud Tiering 서비스로 직접 이동하여 설정할 수 있습니다. 


| 스토리지를 프로비저닝하려면 먼저 Cloud Manager에서 ONTAP 클러스터를 검색해야 합니다. 검색이 완료되면 작업 환경을 열어 스토리지를 프로비저닝해야 합니다. | 먼저 Cloud Manager에서 ONTAP 클러스터를 검색한 다음 작업 환경을 열어 스토리지 프로비저닝을 시작합니다. 간단합니다! | Cloud Manager에서 ONTAP 클러스터를 검색하고 작업 환경을 열어 스토리지를 프로비저닝합니다. 


| 분석할 항목에 따라 두 가지 방법 중 하나로 스토리지 시스템의 상태 특성을 분석합니다. 대시보드에서 wellness 속성 위젯을 선택하거나 모두 보기를 선택하여 전체 웰빙 특성 목록을 볼 수 있습니다. | 시스템의 웰니스 특성을 분석하는 두 가지 방법이 있습니다. 대시보드에서 웰니스 특성 위젯을 선택하십시오. 또는 하나의 보기에 전체 웰빙 속성 목록이 표시되는 경우 모두 보기 를 선택합니다. | 대시보드에서 건강 상태 속성 위젯을 선택하거나 모두 보기 를 선택하여 모든 조치 및 위험 목록을 표시합니다. 


| 설정 마법사가 시작되면 마법사의 지시에 따라 노드를 설정하고 클러스터에 연결합니다. 다음 단계에서는 마법사의 단계를 안내합니다. | 설치 마법사가 나타나(거의 마법과 유사) 노드를 설정하고 클러스터에 결합하는 간단한 프로세스를 안내합니다. | 설치 마법사의 지침에 따라 노드를 설정하고 클러스터에 연결합니다. 


| 여러 콘텐츠 형식 유형 중에서 선택하여 새 시스템을 설치하고 설정할 수 있습니다. 각 형식 유형은 전체 지침을 제공합니다. 원하는 학습 방법과 가장 일치하는 형식 유형을 선택합니다. | 시스템을 어떻게 설정 및 설치하시겠습니까? 여러 콘텐츠 형식 유형의 지침을 제공하지만 원하는 학습 방법은 알고 있는 경우에만 제공됩니다. | 시스템 설치 및 설정 과정을 안내하는 콘텐츠 형식 유형을 선택하십시오. 
|===


== 간단한 쓰기

크고 혼란스러운 단어는 피하십시오. 단순성 유지 당신은 전문 동료에게 무언가를 설명하지만 어휘를 드러내 보이지 않습니다.

** 대신**: “NetApp Cloud Central 계정에서 사용자를 해리.”

** 다음과 같이 하십시오.**: “NetApp Cloud Central 계정에서 사용자를 제거하십시오.”



== 최소한의 글쓰기

짧고 단순한 문장으로 콘텐츠를 읽기 쉽게 만들거나 스캔할 수 있습니다. 이제 더 긴 문장을 사용하되 더 짧은 문장을 사용하는 것이 좋습니다. 이렇게.

** 대신**: “AWS의 Cloud Volumes ONTAP 시스템과 다른 네트워크의 ONTAP 시스템 간에 데이터를 복제하려면 Azure VPC와 다른 네트워크(예: Azure VNET 또는 회사 네트워크) 간에 VPN 연결이 있어야 합니다.”

** 이렇게 합니다**: “네트워크 간 데이터 복제에는 VPN을 통한 연결이 필요합니다. 예를 들어, Amazon VPC와 기업 네트워크 간 또는 AWS와 Azure 간에 연결할 수 있습니다."

도 참조하십시오 <<minimalism>>.



== 쓰기 활성

수동 음성 피하는 것은 기술 문서 작성의 표준 규칙이지만 대화 내용을 전달할 때는 활성 음성을 사용하는 것이 특히 중요합니다.

이** 대신**: “첫 번째 클러스터를 배포하기 전에 필요한 권한을 제공해야 합니다.”

** 이 작업을 수행하십시오.**: “첫 번째 클러스터를 배포하기 전에 필요한 권한을 제공합니다.”

도 참조하십시오 <<active voice (versus “passive voice”)>>.



== 포용적인 언어를 사용합니다

NetApp은 제품 설명서에 차별적이고 독점적인 언어가 포함되어 있지 않아야 한다고 생각합니다. 우리가 사용하는 말은 고객과 긍정적인 관계를 형성하거나 고객을 소외시키는 데 차이가 있습니다. 특히 문구에서는 영향력이 의도보다 더 중요합니다.

NetApp 제품의 콘텐츠를 만들 때 성능 저하, 인종주의, 현증 또는 기타 강압으로 해석될 수 있는 언어는 피해야 합니다. 대신, 문서를 사용해야 하는 모든 사람이 액세스할 수 있고 환영하는 언어를 사용하십시오. 예를 들어, "마스터/슬레이브" 대신 "기본/보조"를 사용합니다.

우리는 문서와 당사 제품에서 모든 비포용적인 언어를 제거하기 위해 최선을 다 한다는 것을 알고 있습니다. NetApp은 자사의 표준 및 모범 사례를 적극적으로 활용하고 있으며 이 섹션을 향후 추가 지침으로 업데이트할 예정입니다.



== 요점을 확인합니다

사용자에게 중요한 것부터 시작합니다. 사용자가 어떤 일을 하고 있는지 알아보고 그 목표를 달성하도록 돕는 데 초점을 맞춥니다.

이** 대신**: “Cloud Sync는 전송 중인 데이터 암호화를 사용하여 NFS 서버 간에 데이터를 동기화할 수 있습니다. 네트워크를 통해 데이터를 전송하기 위한 엄격한 보안 정책이 있는 경우 데이터를 암호화하는 것이 도움이 될 수 있습니다."

** 수행 방법**: “회사에 엄격한 보안 정책이 있는 경우 전송 중인 데이터 암호화를 사용하여 다른 네트워크의 NFS 서버 간에 데이터를 동기화합니다.”



== 많은 시각 자료를 사용합니다

대부분의 사람들은 시각적 학습자를 나타냅니다. 비디오, 다이어그램 및 스크린샷을 사용하여 학습 개선 시각 자료는 텍스트 블록을 분할하는 데도 도움이 됩니다.

.예
* https://docs.netapp.com/us-en/occm/concept_accounts_aws.html["예 #1"^]
* https://docs.netapp.com/us-en/occm/task_getting_started_azure.html["예 #2"^]


도 참조하십시오 <<graphics>>.



== 스캔 가능한 콘텐츠를 만듭니다

제목, 목록 및 표를 사용하면 사용자가 원하는 항목을 검색할 수 있습니다.

.예
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["예 #1"^]
* https://docs.netapp.com/us-en/cloud_volumes/aws/reference_selecting_service_level_and_quota.html["예 #2"^]




== 사용자 목표 또는 해당 목표의 특정 측면에 초점을 맞춥니다

일련의 작업을 완료하는 방법을 설명하는 경우 개념 및 참조 기반 정보를 포함하여 일련의 섹션에 모든 작업을 한 페이지에 배치합니다. 페이지를 너무 많이 클릭해야 하는 여러 개의 미니 페이지로 나누지 마십시오. 동시에 길고 위협적인 페이지를 만들지 마십시오. 페이지가 너무 긴 경우 최선의 판단력을 발휘하여 결정합니다.

.예
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["예 #1"^]
* https://docs.netapp.com/us-en/occm/concept_ha.html["예 #2"^]




== 사용자의 목표에 맞게 콘텐츠를 구성합니다

사용자가 필요할 때 필요한 정보를 찾을 수 있도록 도와줍니다. 다음과 같이 콘텐츠를 구성하여 가능한 한 빨리 문서를 통해 문서를 주고 받을 수 있습니다.

좌측 내비게이션의 첫 번째 항목(고급):: 사용자가 달성하려는 목표에 따라 콘텐츠를 구성합니다. 예를 들어, 데이터 시작 또는 보호.
탐색의 두 번째 항목(중간 수준):: 목표를 구성하는 광범위한 작업을 중심으로 콘텐츠를 구성합니다. 예를 들어 재해 복구 설정 또는 데이터 보호 설정 등이 있습니다.
개별 페이지(상세 수준):: 광범위한 작업을 구성하는 개별 작업에 대한 콘텐츠를 구성합니다. 각 작업은 하나의 학습에 집중하거나 광범위한 작업의 측면을 수행하는 데 중점을 두고 있습니다. 예를 들어 재해 복구를 설정하는 데 필요한 작업이 있습니다.




== 글로벌 고객을 위한 글을 작성합니다

전 세계 고객과 파트너를 위해 글을 쓰고 있으며, 대부분의 컨텐츠는 인공신경망 기계 번역 도구나 번역으로 번역됩니다. 다음 지침을 따라 보다 명확한 문서를 작성하고 번역이 보다 쉬워집니다.

* 짧고 간단한 문장을 쓰십시오.
* 표준 문법 및 구두점 사용
* 한 단어에는 한 단어를 사용하고 한 단어에는 한 단어를 사용합니다.
* 일반적인 자궁 수축 사용.
* 그래픽을 사용하여 텍스트를 명확하게 표시하거나 바꿉니다.
* 그래픽에 텍스트를 포함하지 않도록 합니다.
* 문자열에 3개 이상의 명사를 사용하지 마십시오.
* 명확하지 않은 선행 기술을 피합니다.
* 전문 용어, 구어적 표현 및 은유를 피하십시오.
* 비기술적 예는 피하십시오.
* 하드 리턴과 간격을 사용하지 마십시오.
* 유머나 아이러니를 사용하지 마십시오.
* 차별적인 내용을 사용하지 마십시오.
* 특정 인물을 쓰기 전에는 성별에 편향된 언어를 사용하지 마십시오.




== A-Z 지침



=== 활성 음성("수동 음성"과 비교)

활성 음성의 경우, 문장의 주제는 행동의 실천자:

* 시스템을 부적절하게 종료하면 인터페이스에 경고 메시지가 표시됩니다.
* NetApp이 계약을 수주했습니다.


활성 음성이 또렷하고 또렷하게 메시지를 전달합니다. 수동 음성을 사용해야 하는 특별한 이유가 없는 한 활성 음성 및 주소 사용자를 직접 "사용자"로 사용합니다.

수동적 음성에 있어, 그 조치의 실행자가 불분명하다:

* 시스템이 부적절하게 종료될 경우 경고 메시지가 표시됩니다.
* NetApp이 계약을 체결했습니다.


다음과 같은 경우 수동 음성 사용:

* 누가 어떤 조치를 취했는지, 무엇을 수행했는지 알 수 없습니다.
* 당신은 작업 결과에 대해 사용자 책임을 회피하려고 합니다.
* 일부 필수 구성 요소 정보와 같이 이 정보를 쓸 수 없습니다.


추가 동사 규칙은 다음을 참조하십시오.

* https://docs.microsoft.com/en-us/style-guide/welcome/["Microsoft 작성 스타일 가이드"^]
* https://www.chicagomanualofstyle.org/home.html["시카고 스타일 설명서"^]
* https://www.merriam-webster.com/["메리암 - 웹스터 사전 온라인"^]




=== 주의

다음 레이블을 사용하여 기본 콘텐츠 흐름과 별도로 콘텐츠를 식별합니다.

* 참고
+
나머지 텍스트와 구분되어야 하는 중요한 정보는 참고를 사용하십시오. 사용자가 작업에 대해 배우거나 작업을 완료하는 데 필요하지 않은 "알기 좋은" 정보에 대해서는 참고를 사용하지 마십시오.

* 팁
+
항상 모범 사례 정보를 기본적으로 문서화하는 것이 당사의 정책이므로 팁을 가급적 사용하지 마십시오. 필요한 경우 팁을 사용하여 사용자가 제품을 사용하거나 단계 또는 작업을 쉽고 효율적으로 완료할 수 있도록 도와주는 모범 사례 정보를 포함합니다.

* 주의
+
사용자에게 치명적이거나 극히 위험한 신체 상해가 발생할 수 있는 조건이나 절차에 대해 경고하려면 주의를 기울이십시오.





=== 이후("1회" 대비)

* “After(이후)”를 사용하여 “컴퓨터를 연결한 후 컴퓨터를 켭니다.”라는 연대순으로 표시합니다.
* “한 번”은 “한 번”을 의미합니다.




=== 또한

* "추가"를 의미하려면 "또한"를 사용하십시오.
* "또는"을 사용하여 "대체"를 의미하지 마십시오.




=== 및/또는

더 정확한 용어가 있으면 선택합니다. 두 용어 중 어느 것도 다른 용어보다 정확하지 않은 경우 " 및/또는 "를 사용합니다.



=== 현재

"이유"를 의미하는 "있는 그대로"를 사용하지 마십시오.



=== 사용("사용" 또는 "사용")

* 를 사용하는 엔터티가 제목인 경우 "사용"을 사용합니다. "구성 요소 메뉴를 사용하여 리포지토리에 새 구성 요소를 추가할 수 있습니다."
* "사용" 또는 "사용"으로 문장을 시작할 수 있습니다. 제품 이름은 "SnapDrive을 사용하면 Windows 환경에서 가상 디스크와 스냅샷 복사본을 관리할 수 있습니다."로 허용됩니다.




=== CAN("있을 수 있음", "할 수 있음", "해야 함" 또는 "필수")

* "CAN"을 사용하여 "이 절차 중 언제든지 변경 내용을 커밋할 수 있습니다."라는 기능을 나타냅니다.
* 가능성을 나타내려면 "가능성"을 사용합니다. "여러 프로그램을 다운로드하면 처리 시간에 영향을 줄 수 있습니다."
* 기능이나 권한을 의미할 수 있으므로 모호한 "5월"을 사용하지 마십시오.
* 권장되지만 선택 가능한 작업을 나타내려면 "필수"를 사용합니다. 대신 "권장"과 같은 대체 문구를 사용하는 것이 좋습니다.
* 수동적인 "필수"를 사용하지 마십시오. 명령적 음성을 사용하여 생각을 지침으로 다시 언급하십시오. "필수"를 사용하는 경우 이를 사용하여 필요한 조치 또는 조건을 나타냅니다.




=== 대문자 표시

거의 모든 항목에 문장 스타일의 대문자 표시(소문자)를 사용합니다. 자본만:

* 표 제목을 포함한 문장과 제목의 첫 번째 단어입니다
* 문장 조각을 포함한 목록 항목의 첫 번째 단어
* 적절한 명사
* 문서 제목 및 자막(5자 이상의 모든 주요 단어 및 사전 위치 사용)
* UI 요소(인터페이스에서 대문자로 표시된 경우에만 해당) 그렇지 않으면 소문자로 사용하십시오.




=== 주의 사항

사용자에게 치명적이거나 극히 위험한 신체 상해가 발생할 수 있는 조건이나 절차에 대해 경고하려면 주의를 기울이십시오.

을 참조하십시오 <<admonitions>> 기본 콘텐츠 흐름과 별도로 콘텐츠를 식별하는 기타 레이블입니다.



=== 정합성

“전문 동료에게 무언가를 설명할 때 말하는 것처럼 쓰십시오.”는 모든 사람에게 다른 것을 의미합니다. 전문적인 대화 스타일을 통해 사용자와 연결하고 여러 명의 기고자들 사이에서 사소한 불일치를 자주 볼 수 있습니다.

* 콘텐츠를 명확하고 쉽게 만드는 데 집중합니다. 모든 콘텐츠가 명확하고 사용하기 쉬운다면 사소한 불일치는 문제가 되지 않습니다.
* 작성 페이지 내에서 일관성을 유지합니다.
* 항상 의 지침을 따르십시오 <<Write for a global audience>>.




=== 자궁 수축

수축은 대화 분위기를 강화하며 많은 수축은 이해하고 번역하기 쉽습니다.

* 다음과 같은 금기 작업을 사용합니다. 이해 및 번역이 쉽습니다.
+
|===


| 아닙니다 | 바로 여러분입니다 


| 그렇지 않습니다 | 우리는 


| 그렇지 않았습니다 | 바로 그것입니다 


| 그렇지 않았습니다 | 자, 그럼 


| 그렇지 않았습니다 | (향후 시제가 필요한 경우) 


| 그렇지 않습니다 | 안 함(향후 시제가 필요한 경우) 


| 하지 마십시오 | (향후 시제가 필요한 경우) 
|===
* 이해 및 번역이 어려운 다음과 같은 금기사항은 사용하지 마십시오.
+
|===


| 있습니다 | 필요합니다 


| 필요 없습니다 | 필요 없습니다 


| 그럴 수도 있습니다 | 할 수 없습니다 
|===




=== 확인("확인" 또는 "확인"과 비교)

* "확인"을 사용하여 "확인"을 말합니다. "해당"을 적절히 포함시키십시오. "그림 주위에 충분한 공백이 있는지 확인하십시오."
* 약속이나 보장을 암시하기 위해 "확인"을 사용하지 마십시오. "ONTAP 클러스터에서 NFS 및 CIFS 볼륨을 프로비저닝할 수 있도록 Cloud Manager를 사용하십시오."
* 사용자가 이미 존재하거나 이미 발생한 작업을 두 번 확인해야 함을 의미하는 경우 "확인" 또는 "확인"을 사용합니다. "NFS가 클러스터에 설정되어 있는지 확인"




=== 그래픽

유용한 일러스트레이션, 다이어그램, 흐름도, 화면 캡처 또는 기타 시각적 참조를 포함할 수 있는 기회를 위해 콘텐츠를 지속적으로 평가합니다. 그래픽은 종종 텍스트보다 복잡한 개념과 단계를 보다 명확하게 전달합니다.

* 그림의 통신 용도를 설명하십시오. “다음 그림은 후면 패널의 AC 전원 공급 장치 LED를 보여줍니다.
* 그림 위치를 "위" 또는 "아래"가 아닌 "다음" 또는 "이전"으로 참조하십시오.




=== 문법

달리 명시된 경우를 제외하고 다음에 설명된 문법, 문장 부호 및 맞춤법 규칙을 따릅니다.

* https://docs.microsoft.com/en-us/style-guide/welcome/["Microsoft 작성 스타일 가이드"^]
* https://www.chicagomanualofstyle.org/home.html["시카고 스타일 설명서"^]
* https://www.merriam-webster.com/["메리암 - 웹스터 사전 온라인"^]




=== 그렇지 않은 경우

"그렇지 않은 경우" 그 자체로 이전 문장을 참조하지 마십시오.

이** 대신**: “컴퓨터가 꺼져 있어야 합니다. 그렇지 않으면 끄십시오.”

** 다음을 수행하십시오.**: "컴퓨터가 꺼져 있는지 확인하십시오."



=== IF("여부" 또는 "시기")

* "If this, then" 구조물과 같은 조건을 나타내려면 "If" 를 사용합니다.
* 명시적이거나 묵시적이거나 "없는" 조건이 있는 경우 "여부"를 사용합니다. 번역의 편의를 위해 "여부"를 "여부"만으로 바꾸는 것이 가장 좋습니다.
* "시기"를 사용하여 경과 시간을 표시합니다.




=== 필수 음성

* 사용자 작업 목록에 대한 단계, 지침, 요청 및 제목에 필수 음성을 사용합니다.
+
** 작업 환경 페이지에서 검색 을 클릭하고 ONTAP 클러스터 를 선택합니다.
** "캠 핸들을 돌려 전원 공급 장치와 수평이 되도록 합니다."


* 수동 음성을 대체하기 위해 명령적 음성 사용을 고려하십시오.
+
이** 대신**: “첫 번째 클러스터를 배포하기 전에 필요한 권한을 제공해야 합니다.”

+
** 이 작업을 수행하십시오.**: “첫 번째 클러스터를 배포하기 전에 필요한 권한을 제공합니다.”

* 필수 음성을 사용하여 개념 및 참조 정보에 단계를 포함시키지 마십시오.




=== IP 및 IPv6 주소

예를 들어 IP 주소(IPv6 포함)의 경우 "10.x"로 시작하는 주소를 포함하는 것이 안전합니다.



=== 향후 기능 또는 릴리즈

기능 또는 기능이 "현재 지원되지 않음"이라고 말하는 것을 제외하고 예정된 제품 릴리스 또는 기능의 시기 또는 내용을 참조하지 마십시오.



=== KB 문서: 참조

해당하는 경우 콘텐츠의 KB(NetApp Knowledgebase) 문서를 참조하십시오. 리소스 페이지 및 GitHub 콘텐츠를 보려면 링크를 러닝 텍스트에 넣으십시오.



=== 목록

일반적으로 정보 목록은 텍스트 블록보다 스캔하고 흡수하기 쉽습니다. 복잡한 정보를 목록 형식으로 제공하여 단순화하는 방법을 고려하십시오. 다음은 몇 가지 일반적인 지침입니다. 하지만 여러분의 판단력을 발휘해 보십시오.

* 목록의 이유가 명확한지 확인합니다. 전체 문장, 결장이 있는 문장 조각 또는 제목이 있는 목록을 소개합니다.
* 목록은 2개에서 7개 사이의 항목을 포함해야 합니다. 일반적으로 각 항목의 정보가 짧을수록 목록을 스캔 가능한 상태로 유지하면서 더 많은 항목을 추가할 수 있습니다.
* 목록 항목은 가능한 한 스캔 가능한 상태여야 합니다. 목록 항목을 스캔 가능한 상태로 유지하는 방식으로 텍스트 블록을 사용하지 않도록 합니다.
* 목록 항목은 대문자로 시작해야 하며 목록 항목은 문법적으로 평행해야 합니다. 예를 들어, 각 항목을 명사 또는 동사로 시작합니다.
+
** 모든 목록 항목이 완전한 문장이면 마침표로 끝마치십시오.
** 모든 목록 항목이 문장 조각인 경우 마침표로 끝내지 마십시오.


* 목록 항목은 사전순 또는 시간순으로 정렬됩니다.




=== 로컬리제이션

을 참조하십시오 <<Write for a global audience>>.



=== 미니멀리즘

* 현재 사용자가 이 위치에서 이 콘텐츠를 필요로 합니까?
* 너무 공식적이거나 지나치게 캐주얼한 것 없이 컨텐츠를 더 적은 단어로 표현할 수 있습니까?
* 긴 문장을 줄이거나 단순화하거나 두 개 이상의 문장으로 나눌 수 있습니까?
* 목록을 사용하여 콘텐츠를 보다 스캔 가능하게 만들 수 있습니까?
* 그래픽을 사용하여 텍스트 블록을 보강하거나 바꿀 수 있습니까?




=== 참고 정보

나머지 텍스트와 구분되어야 하는 중요한 정보는 참고를 사용하십시오. 사용자가 작업에 대해 배우거나 작업을 완료하는 데 필요하지 않은 "알기 좋은" 정보에 대해서는 참고를 사용하지 마십시오.

을 참조하십시오 <<admonitions>> 기본 콘텐츠 흐름과 별도로 콘텐츠를 식별하는 기타 레이블입니다.



=== 번호

* 10보다 큰 숫자와 10보다 큰 모든 숫자에 아라비아 숫자를 사용합니다. 단, 다음 경우는 예외입니다.
+
** 문장에 숫자를 사용할 경우 아라비아 숫자가 아닌 단어를 사용합니다.
** 숫자(숫자 아님)를 사용하여 대략적인 숫자를 확인하십시오.


* 10보다 작은 숫자에 단어를 사용합니다.
* 문장에 10보다 작은 숫자와 10보다 큰 숫자가 혼합되어 있는 경우 모든 숫자에 아라비아 숫자를 사용합니다.
* 추가 숫자 표기 규칙은 다음을 참조하십시오.
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["Microsoft 작성 스타일 가이드"^]
** https://www.chicagomanualofstyle.org/home.html["시카고 스타일 설명서"^]






=== 표절

NetApp 제품과 NetApp 제품의 상호 작용 및 타사 제품을 문서화합니다. 타사 제품은 문서화되지 않습니다. 타사 콘텐츠를 복사하여 문서에 붙여 넣을 필요가 없으며 절대 그렇게 해서는 안 됩니다.



=== 필수 구성 요소

전제 조건 현재 작업을 시작하기 전에 사용자가 완료해야 하는 조건이나 작업을 식별합니다.

* "전제 조건", "시작하기 전에" 또는 "시작하기 전에"와 같은 제목으로 콘텐츠의 특성을 식별합니다.
* 다음과 같은 경우 수동 음성을 사용하여 사전 요구 사항을 확인합니다.
+
** "NFS 또는 CIFS가 클러스터에 설정되어 있어야 합니다."
** "클러스터를 Cloud Manager에 추가하려면 클러스터 관리 IP 주소와 admin 사용자 계정의 암호가 있어야 합니다."


* 필요에 따라 사전 요구 사항을 설명합니다. "클러스터에 NFS 또는 CIFS를 설정해야 합니다. System Manager 또는 CLI를 사용하여 NFS 및 CIFS를 설정할 수 있습니다.”
* 현재 작업의 첫 번째 단계로 콘텐츠를 다시 사용하는 것이 적절한지와 같은 다른 방법으로 정보를 표시할 수 있습니다.
+
** 전제 조건: “첫 번째 클러스터를 배포하기 전에 필요한 권한이 있어야 합니다.”
** 단계: “첫 번째 클러스터를 배포하는 데 필요한 권한을 제공합니다.”






=== 이전("이전", "이전" 또는 "이전")

* 가능한 경우 “Prior(이전)”를 “Before(이전)”로 교체합니다.
* "이전"을 사용할 수 없는 경우, "이전"을 형용사로 사용하여 이전에 발생했거나 중요도가 높은 항목을 참조합니다.
* "Previous(이전)"를 사용하여 지정되지 않은 시간 이전에 발생한 항목을 나타냅니다.
* "선행"을 사용하여 즉시 발생한 사항을 나타냅니다.




=== 구두점

단순성 유지 일반적으로 문장에 구두점이 더 많이 포함할수록 이해에 더 많은 뇌 세포가 필요합니다.

* 세 개 이상의 항목의 내러티브 목록에 각 항목 앞에 일련 번호 쉼표(Oxford 쉼표)를 사용하십시오("and" 또는 " or").
* 세미콜론과 콜론의 사용을 제한합니다.
* 달리 명시된 경우를 제외하고 다음에 설명된 문법, 문장 부호 및 맞춤법 규칙을 따릅니다.
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["Microsoft 작성 스타일 가이드"^]
** https://www.chicagomanualofstyle.org/home.html["시카고 스타일 설명서"^]
** https://www.merriam-webster.com/["메리암 - 웹스터 사전 온라인"^]






=== 그 이후로

“since”를 사용하여 시간 경과를 표시합니다. "이유"를 의미하는 "이후"를 사용하지 마십시오.



=== 맞춤법

달리 명시된 경우를 제외하고 다음에 설명된 문법, 문장 부호 및 맞춤법 규칙을 따릅니다.

* https://docs.microsoft.com/en-us/style-guide/welcome/["Microsoft 작성 스타일 가이드"^]
* https://www.chicagomanualofstyle.org/home.html["시카고 스타일 설명서"^]
* https://www.merriam-webster.com/["메리암 - 웹스터 사전 온라인"^]




=== 해당("어느" 또는 "누가")

* "that"(뒤에 오는 쉼표 제외)를 사용하여 문장이 이해되는 데 필요한 절을 도입합니다.
* "컴퓨터 전원이 꺼져 있는지 확인하십시오."라는 메시지가 영어로 표시되지 않더라도 "해당"을 사용합니다.
* 참고 정보를 추가하지만 문장이 이해하기 위해 필요하지 않은 절을 소개하려면 "다음"(뒤에 오는 쉼표)를 사용합니다.
* "WHO"를 사용하여 사람을 지칭하는 절을 소개합니다.




=== 팁 정보

항상 모범 사례 정보를 기본적으로 문서화하는 것이 당사의 정책이므로 팁을 가급적 사용하지 마십시오. 필요한 경우 팁을 사용하여 사용자가 제품을 사용하거나 단계 또는 작업을 쉽고 효율적으로 완료할 수 있도록 도와주는 모범 사례 정보를 포함합니다.

을 참조하십시오 <<admonitions>> 기본 콘텐츠 흐름과 별도로 콘텐츠를 식별하는 기타 레이블입니다.



=== 상표

당사 템플릿에 포함된 법적 진술이 충분하기 때문에 대부분의 기술 콘텐츠에는 상표 기호를 포함하지 않습니다. 그러나 을 사용할 때는 모든 사용 규칙을 따릅니다 https://www.netapp.com/us/legal/netapptmlist.aspx["NetApp 상표 용어"^]:

* 상표 용어(기호 포함 또는 제외)는 명사, 동사 또는 자세한 말로 사용할 수 없으며 형용사로만 사용하십시오.
* 상표 용어를 축약하거나 하이픈을 넣거나 기울임꼴로 표시하지 마십시오.
* 상표가 등록된 용어를 비약적으로 사용하지 마십시오. 복수 형식이 필요한 경우 상표 이름을 복수 명사를 수정하는 형용사로 사용합니다.
* 상표가 있는 용어의 소유격 형태를 사용하지 마십시오. 상표가 아닌 일반적인 의미에서 NetApp 같은 소유 형태의 회사 이름을 사용할 수 있습니다.




=== 사용자 인터페이스

인터페이스를 최대한 많이 사용하여 사용자를 안내합니다.



==== 일반 지침

UI를 문서화하는 당사의 스타일은 간단하고 최소화됩니다.

* 사용자가 콘텐츠를 읽는 동안 인터페이스를 사용하고 있다고 가정합니다.
* 인터페이스를 통해 사용자를 안내합니다.
+
** 마법사 또는 화면을 단계별로 안내하지 마십시오. 인터페이스에서 명확하게 드러나지 않는 중요한 사항만을 말합니다.
** "확인 클릭" 또는 "저장 클릭" 또는 "볼륨이 생성됨" 또는 작업을 수행하는 사람에게 명백한 다른 작업은 포함하지 마십시오.
** 성공을 거십시오. 대부분의 시간에 작업이 실패할 것으로 예상되지 않는 한, 실패 경로를 문서화하지 마십시오. 인터페이스가 적절한 지침을 제공한다고 가정합니다.


* "클릭"을 전혀 사용하지 마십시오. 이 단어는 마우스, 터치, 키보드 및 기타 선택 방법을 포함하므로 항상 "선택"을 사용하십시오.
* 고객 사용 사례를 다루고 워크플로우를 시작하기 위해 인터페이스의 적절한 위치로 사용자를 배치하는 워크플로에 콘텐츠를 집중합니다.
* 사용자 목표를 달성할 수 있는 가장 좋은 방법을 항상 문서화하십시오.
* 워크플로에 상당한 결정이 필요한 경우 결정 규칙을 문서화해야 합니다.
* 대부분의 사용자에게 필요한 최소 단계 수를 사용합니다.




==== UI 요소 이름 지정

UI 요소의 이름을 지정해야 하는 세분화 수준으로 문서화하지 마십시오. 인터페이스에 의존하여 상호작용의 세부 사항을 사용자에게 안내합니다. 특정 이름을 지정해야 하는 경우 요소의 레이블 이름을 지정합니다. 예를 들어, “원하는 볼륨 선택” 또는 “기존 볼륨 사용”을 선택합니다. 메뉴나 라디오 버튼 또는 확인란에 이름을 지정할 필요가 없습니다. 라벨만 사용하십시오.

사용자가 선택해야 하는 아이콘의 경우 아이콘 이미지를 사용합니다. 이름을 지정하지 마십시오. 이 규칙은 화살표, 연필, 기어, kabob, hamburger, 등.



==== 표시된 라벨을 나타냅니다

레이블을 식별할 때 사용자 인터페이스에서 사용하는 철자 및 대/소문자를 따릅니다. 레이블 뒤에 타원이 오는 경우 개체의 이름을 지정할 때 타원을 포함하지 마십시오. 개발자가 쉽게 작성할 수 있도록 사용자 인터페이스 레이블에 제목 스타일의 대문자 표시를 사용하도록 권장합니다.



==== 화면 캡처 사용

간헐적인 화면 캡처("스크린샷")를 통해 사용자는 워크플로 중에 인터페이스를 시작하거나 변경할 때 인터페이스에서 올바른 위치에 있다는 확신을 가질 수 있습니다. 입력할 데이터 또는 선택할 값을 표시하기 위해 화면 캡처를 사용하지 마십시오.



=== While("계속")

* "While"을 사용하여 시간 내에 발생한 것을 나타냅니다.
* 거의 동시에 발생하거나 다른 활동 직후에 발생하는 활동을 나타내려면 "하지만"을 사용합니다.




=== 워크플로우

사용자는 콘텐츠를 읽고 특정 목표를 달성합니다. 사용자는 필요한 콘텐츠를 찾고, 목표를 달성하고, 가족 단위로 이동하기를 원합니다. 제품 또는 기능을 문서로 작성하는 것이 아니라 사용자 목표를 기록하는 것이 우리의 임무입니다. 워크플로는 사용자가 목표를 달성하는 데 가장 직접적인 방법입니다.

워크플로는 사용자 목표를 달성하는 방법을 설명하는 일련의 단계 또는 하위 작업입니다. 워크플로의 범위는 완전한 목표입니다.

예를 들어, 볼륨을 생성하는 단계는 완전한 목표가 아니므로 워크플로가 아닙니다. ESX Server에서 스토리지를 사용할 수 있도록 하는 단계는 워크플로우일 수 있습니다. 이 단계에는 볼륨 만들기는 물론 볼륨 내보내기, 필요한 사용 권한 설정, 네트워크 인터페이스 만들기 등이 포함됩니다. 워크플로우가 고객 사용 사례에서 파생됩니다. 워크플로는 목표 달성을 위한 최상의 방법을 하나만 표시합니다.
